- name: Ensure Debian family
  ansible.builtin.assert:
    that:
      - ansible_facts['os_family'] == "Debian"
    fail_msg: "This role supports only Debian/Ubuntu."

- name: Ensure apt keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Download Kubernetes GPG key
  ansible.builtin.get_url:
    url: "https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/Release.key"
    dest: /etc/apt/keyrings/kubernetes.asc
    mode: "0644"
    timeout: 60
  environment: >-
    {{
      {
        'http_proxy': proxy_http_url,
        'https_proxy': proxy_http_url,
        'HTTP_PROXY': proxy_http_url,
        'HTTPS_PROXY': proxy_http_url,
        'no_proxy': proxy_no_proxy,
        'NO_PROXY': proxy_no_proxy
      } if kubernetes_use_proxy | bool else {}
    }}
  register: kubernetes_key_download
  retries: 3
  delay: 5
  until: kubernetes_key_download is succeeded

- name: Dearmor Kubernetes GPG key
  ansible.builtin.command: >
    gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /etc/apt/keyrings/kubernetes.asc
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add Kubernetes repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/ /
    filename: kubernetes
    state: present
    update_cache: false
  environment: >-
    {{
      {
        'http_proxy': proxy_http_url,
        'https_proxy': proxy_http_url,
        'HTTP_PROXY': proxy_http_url,
        'HTTPS_PROXY': proxy_http_url,
        'no_proxy': proxy_no_proxy,
        'NO_PROXY': proxy_no_proxy
      } if kubernetes_use_proxy | bool else {}
    }}

- name: Install Kubernetes packages
  ansible.builtin.apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: true
  environment: >-
    {{
      {
        'http_proxy': proxy_http_url,
        'https_proxy': proxy_http_url,
        'HTTP_PROXY': proxy_http_url,
        'HTTPS_PROXY': proxy_http_url,
        'no_proxy': proxy_no_proxy,
        'NO_PROXY': proxy_no_proxy
      } if kubernetes_use_proxy | bool else {}
    }}

- name: Ensure kubelet is enabled and running
  ansible.builtin.service:
    name: kubelet
    state: started
    enabled: true
