- name: Ensure Debian family
  ansible.builtin.assert:
    that: ansible_facts.os_family == "Debian"
    fail_msg: "This role supports only Debian/Ubuntu."

- ansible.builtin.import_tasks: install.yml
  tags: [nfs, install]

- ansible.builtin.import_tasks: configure.yml
  tags: [nfs, configure]
