- ansible.builtin.import_tasks: install.yml
  tags: [zsh, install]

- ansible.builtin.import_tasks: plugins.yml
  tags: [zsh, plugins]

- ansible.builtin.import_tasks: config.yml
  tags: [zsh, config]
