- name: Install zsh plugins
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ zsh_dir }}/{{ item.name }}"
    depth: 1
    recursive: true
    update: true
  loop: "{{ zsh_plugins }}"
  become: true
  become_user: "{{ zsh_user }}"
