- name: Ensure Debian family
  ansible.builtin.assert:
    that: ansible_facts.os_family == "Debian"
    fail_msg: "This role supports only Debian/Ubuntu."

- ansible.builtin.import_tasks: updates.yml
  tags: [updates]

- ansible.builtin.import_tasks: ssh.yml
  tags: [ssh]
  when: base_server_harden_ssh | bool

- ansible.builtin.import_tasks: ufw.yml
  tags: [ufw]
  when: common_firewall_enabled | bool

- ansible.builtin.import_tasks: cleanup.yml
  tags: [cleanup]
  when: base_server_cleanup_autoremove | bool

- ansible.builtin.import_tasks: motd.yml
  tags: [motd]
  when: base_server_manage_motd | bool
