- name: Ensure Debian family
  ansible.builtin.assert:
    that:
      - ansible_facts['os_family'] == "Debian"
    fail_msg: "This role supports only Debian/Ubuntu."

- name: Install Ansible
  ansible.builtin.import_tasks: install_ansible.yml
  tags: [ansible, iac]

- name: Install Terraform
  ansible.builtin.import_tasks: install_terraform.yml
  when: iac_provider == 'terraform'
  tags: [terraform, iac]

- name: Install OpenTofu
  ansible.builtin.import_tasks: install_opentofu.yml
  when: iac_provider == 'opentofu'
  tags: [opentofu, iac]
