# Additional packages for operations nodes.
# Focused on maintenance and basic troubleshooting.
common_packages_extra:
  - gnupg
  - apt-transport-https
  - openssh-client
  - iproute2
  - iputils-ping
  - lsof
  - tree
  - yq
  - nvim
