# Additional packages for sandbox nodes.
common_packages_extra:
  - gnupg
  - apt-transport-https
  - openssh-client
  - socat
  - iproute2
  - iputils-ping
  - dnsutils
  - traceroute
  - lsof
  - strace
  - ncdu
  - yq
  - make
  - build-essential
  - pkg-config
  - golang

# Host-level UFW is intentionally disabled.
common_firewall_enabled: false
