- name: Add k8s nodes to hostfile
  ansible.builtin.blockinfile:
    path: /etc/hosts
    marker: "# {mark} ANSIBLE MANAGED K8S NODES"
    block: |
      {% for host in groups['k8s'] %}
      {{ hostvars[host].ansible_host }} {{ hostvars[host].inventory_hostname }}
      {% endfor %}
    create: true
    backup: true
