- name: Baseline for all VMs
  hosts: vms
  become: true
  tasks:
    - name: Apply common_baseline role
      ansible.builtin.import_role:
        name: common_baseline
      tags: [baseline]

    - name: Apply base_server role
      ansible.builtin.import_role:
        name: base_server
      tags: [base]

- name: Baseline for all containers
  hosts: containers
  become: true
  tasks:
    - name: Apply common_baseline role
      ansible.builtin.import_role:
        name: common_baseline
      tags: [baseline]

    - name: Apply base_container role
      ansible.builtin.import_role:
        name: base_container
      tags: [base]

- name: Docker workers servers
  hosts: docker-workers
  become: true
  tasks:
    - name: Apply docker role
      ansible.builtin.import_role:
        name: docker
      tags: [docker]

- name: Storage servers
  hosts: storage
  become: true
  tasks:
    - name: Apply virtiofs role
      ansible.builtin.import_role:
        name: virtiofs
      tags: [storage]

    - name: Apply nfs-server role
      ansible.builtin.import_role:
        name: nfs-server
      tags: [storage, nfs]

- name: VPN servers
  hosts: vpn
  become: true
  tasks:
    - name: Apply wireguard role
      ansible.builtin.import_role:
        name: wireguard
      tags: [vpn]

- name: Sandbox servers
  hosts: sandbox
  become: true
  tasks:
    - name: Apply zsh role
      ansible.builtin.import_role:
        name: zsh
      tags: [shell]

    - name: Apply docker role
      ansible.builtin.import_role:
        name: docker
      tags: [docker]

- name: SSH trust for all Nodes
  hosts: all
  become: true
  tasks:
    - name: Apply ssh_trust role
      ansible.builtin.import_role:
        name: ssh_trust
      tags: [ssh]

- name: Operations servers
  hosts: operations
  become: true
  tasks:
    - name: Apply zsh role
      ansible.builtin.import_role:
        name: zsh
      tags: [shell]

    - name: Apply fail2ban role
      ansible.builtin.import_role:
        name: fail2ban
      tags: [security]

    - name: Apply ansible role
      ansible.builtin.import_role:
        name: ansible
      tags: [ansible]

    - name: Apply kubernetes_tools role
      ansible.builtin.import_role:
        name: kubernetes_tools
      tags: [kube]

    - name: Apply docker role
      ansible.builtin.import_role:
        name: docker
      tags: [docker]

    - name: Apply docker_context role
      ansible.builtin.import_role:
        name: docker_context
      tags: [docker, docker_context]
