- name: Deploy sshd_config
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0644"
    validate: "{{ ssh_validate_command if ssh_validate_config | bool else omit }}"
  notify: restart ssh
  when: base_container_harden_ssh | bool
