- name: Ensure Debian family
  ansible.builtin.assert:
    that: ansible_facts.os_family == "Debian"
    fail_msg: "This role supports only Debian/Ubuntu."

- ansible.builtin.import_tasks: packages.yml
  tags: [packages]

- ansible.builtin.import_tasks: sysctl.yml
  tags: [sysctl]
