# --- Infrastructure types ---

# Virtual machines
[vms]
vm-sandbox          ansible_host=192.168.1.12
vm-ops-node         ansible_host=192.168.1.13
vm-storage-node     ansible_host=192.168.1.14
vm-k8s-master-1     ansible_host=192.168.1.15
vm-k8s-worker-1     ansible_host=192.168.1.16
vm-k8s-gpu-worker-1 ansible_host=192.168.1.17
vm-docker-worker    ansible_host=192.168.1.18

# LXC containers
[containers]
ct-vpn ansible_host=192.168.1.11

# --- Functional groups ---

# VPN CT
[vpn]
ct-vpn

# Sandbox VM
[sandbox]
vm-sandbox

# Operations VM
[operations]
vm-ops-node

# Storage VM
[storage]
vm-storage-node

# Docker worker VM
[docker-workers]
vm-docker-worker

# k8s VMs
[k8s]
vm-k8s-master-1
vm-k8s-worker-1
vm-k8s-gpu-worker-1

[k8s-master]
vm-k8s-master-1

# GPU VM
[gpu-workers]
vm-k8s-gpu-worker-1
